//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessagesAPI.Gateway
{
    using System;
    using System.Collections.Generic;
    
    public partial class Error
    {
        public int Id { get; set; }
        public Nullable<long> OrderId { get; set; }
        public string ErrorMessage { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public Nullable<System.DateTime> OccuredAt { get; set; }
        public string Identifier { get; set; }
    }
}
