//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessagesAPI.Gateway
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public long Id { get; set; }
        public string Identifier { get; set; }
        public string XmlFile { get; set; }
        public string ResponseXmlFile { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<long> StandardDocumentId { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public Nullable<System.DateTime> ResendDate { get; set; }
        public string AcknowledgementXml { get; set; }
        public Nullable<bool> DoResend { get; set; }
        public string SellerGln { get; set; }
        public string OrderType { get; set; }
        public string ShipToGln { get; set; }
    
        public virtual StandardDocument StandardDocument { get; set; }
        public virtual Status Status { get; set; }
    }
}
