//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessagesAPI.Gateway
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierVendor
    {
        public int Id { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public string Code { get; set; }
        public string Ean { get; set; }
        public string SellerEan { get; set; }
        public Nullable<bool> SystemAdded { get; set; }
        public string Vendor { get; set; }
    
        public virtual Supplier Supplier { get; set; }
    }
}
